### ISSUE TITLE
idea 2020.1.1不能使用，报错内容如下

### ISSUE THREAD

**Issue by blwj127** [xbeeant/spring-java-idea-plugin#2]
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Licensed to IntelliJ IDEA Evaluator
Expiration date: May 25, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Registry: debugger.watches.in.variables=false, compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: GrepConsole, GsonFormat, Lombook Plugin, com.xstudio.com.xstudio.plugin.idea, de.kontext_e.idea.plugins.autofill, com.alibaba.p3c.smartfox, mobi.hsz.idea.gitignore, MavenRunHelper, com.codota.csp.intellij, JRebelPlugin, cn.wuzhizhan.plugin.mybatis

2020-05-12 11:43:19,801 [ 249390]  ERROR - llij.ide.plugins.PluginManager - class com.intellij.psi.impl.source.tree.java.PsiBinaryExpressionImpl cannot be cast to class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl (com.intellij.psi.impl.source.tree.java.PsiBinaryExpressionImpl and com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4f082281)
java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.java.PsiBinaryExpressionImpl cannot be cast to class com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl (com.intellij.psi.impl.source.tree.java.PsiBinaryExpressionImpl and com.intellij.psi.impl.source.tree.java.PsiLiteralExpressionImpl are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4f082281)
	at com.xstudio.plugin.idea.sj.RequestPathUtil.getPath(RequestPathUtil.java:136)
	at com.xstudio.plugin.idea.sj.RequestPathUtil.getRequestPaths(RequestPathUtil.java:75)
	at com.xstudio.plugin.idea.sj.RequestPathUtil.getRequestPath(RequestPathUtil.java:45)
	at com.xstudio.plugin.idea.sj.components.RestListForm$1.actionPerformed(RestListForm.java:24)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6651)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6416)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2020-05-12 11:43:19,801 [ 249390]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.1.1  Build #IU-201.7223.91
2020-05-12 11:43:19,801 [ 249390]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o
2020-05-12 11:43:19,801 [ 249390]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X
2020-05-12 11:43:19,801 [ 249390]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: spring & java tools version: 1.0.2
2020-05-12 11:43:19,801 [ 249390]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowLog

**Comment by beeant0512** [comment]
能否提供您项目中控制器的写法情况，特别是对于 @GetMapping @RequestMapping 这类型的注解 value
的写法，在2020.1.1中我自己的项目还没出现您说的情况

blwj127 <notifications@github.com> 于2020年5月12日周二 上午11:49写道：

**Comment by blwj127** [comment]
@beeant0512 
`
  @RequestMapping(value = {MERCHENT_PREFIX + "/goods/biz/{goodsId}", ADMIN_PREFIX + "/goods/biz/{goodsId}"}, method = RequestMethod.GET)
`

我估计跟这种写法有点关系

**Comment by beeant0512** [comment]
@blwj127 确实有关系，我本地验证了一下你这种写法确实会报错，今天晚上我会先发一个release 官方上架还需要时间

**Comment by beeant0512** [comment]
@blwj127 临时解决了一个版本，IDEA API还有很多不熟悉的地方，比如还不知道怎么获取你定义的常量的值，

**Comment by blwj127** [comment]
@beeant0512  **非常感谢**，1.0.3 解决了我的问题。
